# .travis.yml sets up Travis CI to build & deploy the site.
language: r
sudo: false
cache:
  packages: true
  directories:
  - _cache
git:
  depth: 3
before_install:
  - sudo apt-get install -y r-cran-ncdf4
before_script:
  - git config --global user.name "Tylar Murray (Travis-CI)"
  - git config --global user.email "tylarmurray@mail.usf.edu"
script:
- echo === BUILD ROOT
- Rscript -e 'rmarkdown::render_site()'
- echo === BUILD PAGES DIR
- cp _site.yml pages/_site.yml
- Rscript -e 'rmarkdown::render_site("pages")'
- echo === PUSHING TO GITHUB
- git ls-files -m -o | grep -v '.html' | xargs git add
- git commit -m "travis-ci.org Rmd render [ci skip]"
- git push --force https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:gh-pages

# NOTE: the following deploys the rmarkdown site directly:
# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GH_TOKEN
#   keep-history: true
#   on:
#     branch: master
#   target-branch: gh-pages
#   local-dir: _site
notifications:
  email:
    recipients:
    - tylarmurray@mail.usf.edu
    on_success: change
    on_failure: change
env:
  global:
    secure: KTUpgZtIioDdi9WR4YCOeTuxTqcSdGnhfYJggKQ07mJ82uQNqh4712bkugVKAfMs0idtFbTAx3cVuGSGfxm/PsfYFFZc+RCGDAqx0a7dgYhwcEqkPgh/FqlCVgq+e3/5NfjqKJxkg/NSmTts8CfYvFiLoTYCeaFUgO2JliuJHMo1w1W/dizOMHyRRCtvm0b2hZ3n4511kOxwNaJ2vdCJXAC3P849mhjhhE8Bep56RZNXmPcVl+nnWGyY4t9rmETcayRB0wk48GZGLdW1jbyFa3mSEAXmLTDy4sOkJmz2awxvbU0pA/MYF+ZcAAX8bxZA7U2hS9dFUwY58nxV/EcAJJPFkL4k0WrfTHuH+becYNwU1I83L/9xDsIyCm+8+wucjLHp1v9rA5IdNVBfHLHWGCEqE/biUvbw/hY0hHczmJhTfkraWQ2Fksrr+qXkhknwm6g3OBmyAyrDpBRXl+DOovGLGQPa43R4OcB70vA+l0EmbEJmQ0vIUD/cB9bhhaCJKuK5nPNIqs51CWgrzpGwAikefFBYD2tIqi/4X92UXXWMDVDQQvroeuJkrzjFwslVvtX3NaUr2LYgkl9fELmlVMDjqraVdAjqGmYORxK6XYhqJ6rJ73QZ8YkLqH95G4KE+UX7vWxPFLTyf7hZqdl6YMCbea7AIPRquWx4K3+ineI=
