language: r
sudo: false
cache:
  packages: true
  directories:
  - _cache
git:
  depth: 3
script:
- Rscript -e 'rmarkdown::render_site()'
- git config --global user.name "Tylar Murray (Travis-CI)"
- git config --global user.email "tylarmurray@mail.usf.edu"
- git add -A
- git commit -a -m "Updating website via travis-ci.org [ci skip]"
- git push https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git HEAD:${TRAVIS_BRANCH}
notifications:
  email:
    recipients:
    - bdbest@gmail.com
    on_success: change
    on_failure: always
env:
  global:
    secure: uXmsjhd+R6mG/T1gQWY1EW6kFGcQ+fohb1QWJN5HU6m/4OtHaBYtEcc1/Sug06mdD3XZ56il8kpdFSTx071hOL5bfEdmEevYlE4yhX8bZtV+gAPw135Oyu+Tce1aZ/Ws9hHsE+ujdt+HuKwt4W8neDR2Qjm1r0CrsJo2G0v4M7Wrlyk8u8FZFM9uu2D6ySFv9+5XoUypz+c87jKvBOJygK9X+R97gfuRjl3Wp+IbSYIsnO5hXpuFjRa/cU284y8HbwlCmLaYo2HjqtKurDEFUGFt9gxVzb8Vv9/OyyTjB7/Qmhc3dAOs1lE+btLwiBSktfDK8az1aUhvRQUXTA252ddDP/wrAvkasUHPGkCZjeeJmMhPyPF+fcQMVNZ9bMRVPh0YjH8LkXSHYwO6ZIhfo46L48DYj9XUAvVKY47SpZabo2qLuD2FebBaC1ycZXJlQftH3KCzIOfBmsSsy0UXUm34BEW7dWeElcLgPYT+m3BwwEY59N1jX95+2Padwv8E2I8x3xXsvyjWpBcvaq7c8GH+8q7WlhhWkte5L0aXml01UFpjmTp79JMllFzbN6JTIjxGJoyT6gQwrNfUWiygUeTIpO5mxtVPkJqFlDGRQ0sVJGtJ2tF3b6lI7lwnKQEeuEuaJo3qh30BioGUKZzj1u83MYo2Kbo5MmdBqbBRjIk=
secure: KTUpgZtIioDdi9WR4YCOeTuxTqcSdGnhfYJggKQ07mJ82uQNqh4712bkugVKAfMs0idtFbTAx3cVuGSGfxm/PsfYFFZc+RCGDAqx0a7dgYhwcEqkPgh/FqlCVgq+e3/5NfjqKJxkg/NSmTts8CfYvFiLoTYCeaFUgO2JliuJHMo1w1W/dizOMHyRRCtvm0b2hZ3n4511kOxwNaJ2vdCJXAC3P849mhjhhE8Bep56RZNXmPcVl+nnWGyY4t9rmETcayRB0wk48GZGLdW1jbyFa3mSEAXmLTDy4sOkJmz2awxvbU0pA/MYF+ZcAAX8bxZA7U2hS9dFUwY58nxV/EcAJJPFkL4k0WrfTHuH+becYNwU1I83L/9xDsIyCm+8+wucjLHp1v9rA5IdNVBfHLHWGCEqE/biUvbw/hY0hHczmJhTfkraWQ2Fksrr+qXkhknwm6g3OBmyAyrDpBRXl+DOovGLGQPa43R4OcB70vA+l0EmbEJmQ0vIUD/cB9bhhaCJKuK5nPNIqs51CWgrzpGwAikefFBYD2tIqi/4X92UXXWMDVDQQvroeuJkrzjFwslVvtX3NaUr2LYgkl9fELmlVMDjqraVdAjqGmYORxK6XYhqJ6rJ73QZ8YkLqH95G4KE+UX7vWxPFLTyf7hZqdl6YMCbea7AIPRquWx4K3+ineI=
